### ISSUE TITLE
Xarm calibration issue

### ISSUE THREAD

**Issue by jeoseo** [xArm-Developer/xarm_ros#104]
Hi, this is probably an Xarm problem and not an Xarm ROS problem, but I figured this might be a good place to reach developers. We found that the joints may be off ~5 degrees from their published states.

The following picture is taken with these joint states:
```
<group_state name="home" group="${prefix}xarm7">
<joint name="${prefix}joint1" value="0" />
<joint name="${prefix}joint2" value="-.7" />
<joint name="${prefix}joint3" value="0" />
<joint name="${prefix}joint4" value="0" />
<joint name="${prefix}joint5" value="0" />
<joint name="${prefix}joint6" value=".7" />
<joint name="${prefix}joint7" value="0" />
</group_state>
```
Is there anyway we could re-calibrate the arm?
    
![IMG20220412134323](https://user-images.githubusercontent.com/50963152/163032207-b7620c46-5118-4658-a19b-9580feef8009.jpg)

**Comment by penglongxiang** [comment]
Hi @jeoseo, you mean the reported position is off even in static state right? I can see from this picture that J5 may not be in the zero position. Was the robot in correct position when you first received it and did this robot have any severe collision with the environment?

**Comment by jeoseo** [comment]
Yes, even in the static state. Unfortunately I cannot guarantee that the robot was in the correct position when we first got it, but I am sure we could've knocked it out of alignment as the arm has fallen over before.

**Comment by MinnaZhong** [comment]
Hi Jeoseo,

The zero point of the arm seems to have changed because of the fall, I am afraid we have to get the arm back and calibrate it.
Please provide the SN of the robot to email-minna.zhong@ufactory.cc.
Please make sure the arm is in zero position, and take a picture for us.

**Comment by jeoseo** [comment]
I can take a better picture tomorrow, but how long would this fix take? Sending it from here to China and back would probably make us miss a project deadline.. Is there anyway to change the zero point from here?

**Comment by MinnaZhong** [comment]
Hi Jeoseo,

It's almost impossible to do the calibration by yourself, let me get a better picture and confirm it.
Normally it will take 3 weeks, including repair and shipment.

**Comment by jeoseo** [comment]
This was for a university project, and we ended up completing it with a manual (kind of inaccurate) calibration. Thanks for the feedback though.
