### ISSUE TITLE
Gazebo unable to execute the planned path

### ISSUE THREAD

**Issue by 101Priyansh** [xArm-Developer/xarm_ros#108]
I was trying to work with the xarm7 package. 
The command i am running is: roslaunch xarm7_gripper_moveit_config demo_gazebo.launch
And i try to plan the trajectory using Rviz, it works in Rviz but the motion is not being executing in Gazebo. 
Can you please tell me the solution for it.

**Comment by penglongxiang** [comment]
Hi @101Priyansh, we actually do not have **demo_gazebo.launch** in our original repository, if you need to use moveit with gazebo, please refer [here](https://github.com/xArm-Developer/xarm_ros#to-run-moveit-motion-planner-along-with-gazebo-simulator). You also have the option to add our gripper in the model.
