### ISSUE TITLE
Clearing Servo Error with ROS

### ISSUE THREAD

**Issue by BryanStuurman** [xArm-Developer/xarm_ros#114]
Occasionally, and through my own bad trajectory generation, my robot collides with its environment while in velocity control mode. This generates a "Servo Error" fault (Code S23) which cannot be cleared by a service call to /xarm/moveit_clear_error

What method can I use to clear these errors without using Ufactory Studio?

**Comment by penglongxiang** [comment]
Hi, in case of servo error, you may need to re-enable the motors first. Try `rosservice call /xarm/motion_ctrl 8 1` before moveit_clear_err.

**Comment by BryanStuurman** [comment]
Thanks for the tip, I've tested that out and it works great. 

Thanks for the help.
