### ISSUE TITLE
Joint speed limits

### ISSUE THREAD

**Issue by BryanStuurman** [xArm-Developer/xarm_ros#120]
in [xarm5_moveit_config](https://github.com/xArm-Developer/xarm_ros/tree/master/xarm5_moveit_config)/[config](https://github.com/xArm-Developer/xarm_ros/tree/master/xarm5_moveit_config/config)/joint_limits.yaml the speed limits for each joint are 2.14 radians per second, whereas the actual limits are 3.14 rad/s. 

Can this be increased in the official repo or is there a reason it's kept low?

**Comment by penglongxiang** [comment]
Hi @BryanStuurman, it is just a default value and can be adjusted based on your need. You can also specify the joint accelerations. Thanks.

**Comment by BryanStuurman** [comment]
allright, thanks.
