### ISSUE TITLE
Could not find parameter robot_description on parameter server

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#124]
Hello, I am running a launch file in xarm_ros/xarm_controller/launch named xarm5_control.launch , however I am getting an error. I am using Ubuntu 20.04 and ROS focal 

auto-starting new master
process[master]: started with pid [33605]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 80239b0e-3453-11ed-88d3-d7554270daf0
process[rosout-1]: started with pid [33615]
started core service [/rosout]
process[xarm/traj_controller_spawner-2]: started with pid [33622]
process[robot_state_publisher-3]: started with pid [33623]
[ERROR] [1663176875.966312734]: Could not find parameter robot_description on parameter server
[robot_state_publisher-3] process has died [pid 33623, exit code 1, cmd /opt/ros/noetic/lib/robot_state_publisher/robot_state_publisher /joint_states:=/xarm/joint_states __name:=robot_state_publisher __log:=/home/akumar/.ros/log/80239b0e-3453-11ed-88d3-d7554270daf0/robot_state_publisher-3.log].
log file: /home/akumar/.ros/log/80239b0e-3453-11ed-88d3-d7554270daf0/robot_state_publisher-3*.log

**Comment by penglongxiang** [comment]
Hi, this launch file is not meant to run by itself, it is supposed to be part of [xarm5_beside_table.launch](https://github.com/xArm-Developer/xarm_ros/blob/master/xarm_gazebo/launch/xarm5_beside_table.launch#L45) in xarm_gazebo package. Please **follow our ReadMe** and use the proper launch file to start an application, or to modify the source file to add the parameter loading accordingly. Thanks.
