### ISSUE TITLE
Robot not showing 

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#125]
while running the following command 
roslaunch xarm_description xarm7_rviz_display.launch to test the robot in rviz , my robot is not showing. 

![Screenshot from 2022-09-19 10-24-50](https://user-images.githubusercontent.com/108360879/191042035-656072db-7096-4b45-80d0-ba73e4925a4e.png)

**Comment by penglongxiang** [comment]
Hi, again this launch file is not supposed to be run by itself, please follow the ReadMe, or track its calling files to manually add necessary missing components prior this file.

**Comment by Akumar201** [comment]
The issue has been resolved.

**Comment by anubhavghildiyal** [comment]
Hi @Akumar201 ,
I am getting the same error. Could you tell me how you resolved it? 
Thanks!
