### ISSUE TITLE
Error while connecting robot using ethernet cable

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#128]
Hello, 
I was trying connecting the real robot 6 dof with my computer(Ubuntu 20.04)  but was not able to get connected. However, it was working on windows computer. Do I need to change any security setting on my ubuntu machine ?
I used these two commands 

$ roslaunch xarm7_moveit_config realMove_exec.launch robot_ip:=<your controller box LAN IP address> 
I was getting the following two error 

![IMG_20220920_142740](https://user-images.githubusercontent.com/108360879/191584678-f80e9483-7800-4ced-b95a-148b5fbbcde3.jpg)

![IMG_20220920_142749](https://user-images.githubusercontent.com/108360879/191584815-c53123bf-db00-4da2-be18-77cb80b1c92c.jpg)

**Comment by penglongxiang** [comment]
Please make sure you have followed chapter 3 in ReadMe and properly installed all dependencies. Or provide full log from ROS terminals to us, thanks.

**Comment by Akumar201** [comment]
Hi ! I solved this issue 
1.  on ubuntu we need to go to network setting 
2. Gear icon on Wired opetion 
3. IPv4 and set it to manual 
4. Enter the address , netmask and gateway
