### ISSUE TITLE
Arm striked the ground while using moveit 

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#129]
Hello , I was following the github tutorial using the command to move the arm using Moveit. However , sometimes it strikes the ground. 
I am using this code 

$ roslaunch xarm7_moveit_config realMove_exec.launch robot_ip:=<your controller box LAN IP address> [velocity_control:=false] [report_type:=normal]

**Comment by penglongxiang** [comment]
Hi, could you please provide more information so that we can reproduce on our side? What command did you send to cause the strike? Is there any error code reported by controller?

**Comment by Akumar201** [comment]
Yes, sure 
I am using this command to operate arm in real using ,moveit. it is planning path where it is going under the floor. 

![image](https://user-images.githubusercontent.com/108360879/192541057-8b9e777d-df4a-4fc2-86ca-fc704ba1bbe8.png)

**Comment by penglongxiang** [comment]
... So is there anything wrong? You mean the robot hits the ground because it is commanded to do so (go below ground) ?

**Comment by Akumar201** [comment]
Greetings, Yes It hits the ground, however it should not even in moveit, is there some wrong parameter I am using on moveit or something is wrong with moveit configuration file. In short I would like to know how the robot will know that it can't go beyond the ground level in moveit. 
Thank you

**Comment by penglongxiang** [comment]
In that case you should probably add collision objects as environment configuration to the planning scene. Please check on moveit tutorials.

**Comment by Akumar201** [comment]
Should I create new moveit package or should I edit the given one ?

**Comment by Akumar201** [comment]
This issue can be resolved by two methods, 
1. The easiest way would be to add a box underneath the robot in the URDF that your moveit config is based on.  You could add something like this to your URDF, 

```
<link name="ground_plane_box">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="1.0 1.0 0.5"/> 
        </geometry>
        <material name="Grey">
            <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="1.0 1.0 0.5"/> 
        </geometry>
    </collision>
</link>

<joint name="ground_plane_box" type="fixed">
    <parent link="world" />
    <child link="ground_plane_box" />
    <origin xyz="0 0 -0.25" rpy="0 0 0" />
</joint>
```


2. The second method is to use code to include the object, please visit Adding Objects to the Planning Scene section in https://ros-planning.github.io/moveit_tutorials/doc/move_group_python_interface/move_group_python_interface_tutorial.html#the-entire-code
