### ISSUE TITLE
rqt_Easy_handeye_Hand-eye not working 

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#130]
Greetings, 
I am doing camera calibration using the github tutorial, using the command 

However I am not able to use rqt_Easy_handeye_Hand-eye  for changing the pose so that I can take a sample to do eye in hand calibration. Do I have to move the arm in manual mode to find the transform ? 

![image](https://user-images.githubusercontent.com/108360879/192565390-8a228b73-fc7a-445b-8e6c-d95cdefb6b45.png)

![image](https://user-images.githubusercontent.com/108360879/192619151-b0c8337a-4e2a-42ba-8b4f-86af135d9e04.png)

**Comment by penglongxiang** [comment]
Please try placing the marker in a position facing the camera directly and easy for the arm tool end to change orienation. You can also consult "easy_handeye" developers for further calibration issues, we are not experts.

**Comment by Akumar201** [comment]
I would like to know is something wrong with the movit package, why I am getting this warning. Thank you in advance. 

![image](https://user-images.githubusercontent.com/108360879/192851233-1b5a391e-23cb-43b8-a5ae-cc3b2074b245.png)

**Comment by penglongxiang** [comment]
Hi, could you please provide more information, Did this warning occur only by d435i_xarm_auto_calib.launch? From my side there are no those extra camera links, have you changed anything? Thanks

**Comment by Akumar201** [comment]
Greetings, 
I have not changes anything. I tried running the commands like 
$ roslaunch xarm7_moveit_config realMove_exec.launch robot_ip:=<your controller box LAN IP address> [velocity_control:=false] [report_type:=normal]
but there was no error, this error is occurring only when d435i_xarm_auto_calib.launch?
He was also facing the same issue https://github.com/IFL-CAMP/easy_handeye/issues/98

**Comment by Akumar201** [comment]
Greetings, 
The error was because of realsense camera. I uninstalled the SDK for realsense, got rid of any  error that were coming during sudo apt update or sudo apt upgrade. Reinstall the SDK from https://github.com/IntelRealSense/realsense-ros.
