### ISSUE TITLE
(uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 132

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#131]
Hello, 
I was doing camera calibration following the github demo. However I am getting the following error. I am using extended USB 3 cable for connection. 

![image](https://user-images.githubusercontent.com/108360879/192616653-797f4d00-fec4-4c99-8f45-c98f7cf3656f.png)

With original cable 
 
![image](https://user-images.githubusercontent.com/108360879/192620034-ee19db16-3ac4-455d-9491-638f9bd4a640.png)

I was wondering that this might be because loss of data strength when using long wire so can I switch to simple camera? Any suggestion on cable that would be best suitable for this kind of task where I have to connect my laptop few meters away from the robot.

**Comment by penglongxiang** [comment]
This is clearly realsense related issue, please look for answers in corresponding github page [like this one](https://github.com/IntelRealSense/realsense-ros/issues/2149)  or consult the relevant developers. Thank you.

**Comment by Akumar201** [comment]
To help someone who is going to encounter this error. These error's are regarding connectivity issue, try switching to original cable to troubleshoot it. If you are not getting control_transfer returned error stream continuously you can safely ignore it as the realsense takes up time to establish stable connection with the computer else if it is continuous than check or replace your cable as your connection might be dropping in between causing loss of data.
