### ISSUE TITLE
No objects detected

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#136]
Hello, I was trying to detect 2D Object using the tutorial 
`roslaunch d435i_xarm_setup d435i_findobj2d_xarm_moveit_planner.launch robot_dof:=your_xArm_DOF robot_ip:=your_xArm_IP`
However, it is not able to detect the object, any suggestions that could make detection of 2d object easy ?
![Screenshot from 2022-10-11 14-48-09](https://user-images.githubusercontent.com/108360879/195175897-c7ca0e6d-e489-4474-a4ec-8495aacdfd26.png)
![Screenshot from 2022-10-11 14-44-03](https://user-images.githubusercontent.com/108360879/195175902-6e7d73a4-2c3d-4240-b5fd-38c10a51e6fe.png)
![Screenshot from 2022-10-11 14-43-25](https://user-images.githubusercontent.com/108360879/195175911-98910d4f-15ba-42e2-9da5-47bd0937c9b2.png)

**Comment by penglongxiang** [comment]
I am afraid this is not a question that we can answer. As far as I know, the more complicated texture on the object surface, the  easier for the detection by find_object package. The light condition, object angle and distance would also affect the success of detection.
