### ISSUE TITLE
Does Xarm6 have joint size information for DH modeling?

### ISSUE THREAD

**Issue by AtariaLee** [xArm-Developer/xarm_ros#152]
请问Xarm6有具体的关节长度等详细信息吗？我想进行建立DH参数然后在MATLAB中仿真，但是我在用户手册找不到详细的尺寸信息？请问可以提供吗？

**Comment by penglongxiang** [comment]
Please check the answer here: https://github.com/xArm-Developer/xarm_ros/issues/41#issuecomment-729568902

**Comment by AtariaLee** [comment]
Thanks for your help!
