### ISSUE TITLE
Hand-eye Calibration for LITE 6

### ISSUE THREAD

**Issue by sean880304** [xArm-Developer/xarm_ros#172]
Hi, I currently run the calibration launch file for lite6:

`$ roslaunch d435i_xarm_setup d435i_xarm_auto_calib.launch robot_dof:=6 robot_ip:=192.168.1.xxx`

But the model appears in the RViz seems like xarm6 instead of lite6. Therefore, the plan is not suitable for lite6. Where should I modify to change to lite6 model?

Thanks!!

**Comment by sean880304** [comment]
@Akumar201 Thanks I'll try this out.

**Comment by penglongxiang** [comment]
hi @sean880304 , we have added the corresponding launch file for lite6 calibration with realsense d435i, please check [here](https://github.com/xArm-Developer/xarm_ros#721-hand-eye-calibration-demo-for-ufactory-lite6).

**Comment by sean880304** [comment]
@penglongxiang Thank you, it works now.

**Comment by Murali25111993** [comment]
Hi @Akumar201 ,

I tried with eye_on_hand, working find but I could not able to provide proper quaternion for this below setup. If possible please provide an idea

![Media (1)](https://github.com/user-attachments/assets/a7919ef4-72e5-41d2-8c84-4e932edcc204)
