### ISSUE TITLE
Lite 6 base coordinate distances in relation to base plane

### ISSUE THREAD

**Issue by sean880304** [xArm-Developer/xarm_ros#178]
Hi, as title says, I want to know the exact distances from base coordinate origin to the end of both sides in x and y directions. Below picture is for reference (I want to know the distance marked in blue as well as in the y direction):

Thank you!
![base distances](https://user-images.githubusercontent.com/105100287/226170623-651ff6fd-e9df-4c91-8547-1245d77543ad.png)

**Comment by MinnaZhong** [comment]
Hi Sean,

The distance in blue is 62mm, and in the Y direction is 65mm.
You can download the 3D file on our official website and measure it yourself.
https://www.ufactory.cc/download-lite6-robot

Best regards,
Minna
