### ISSUE TITLE
Pick and Place with Xarm5

### ISSUE THREAD

**Issue by santarone** [xArm-Developer/xarm_ros#19]
Hi there dev team. 
im using xarm5 with ros_melodic 
can i earn some example code or package of pick and place?

**Comment by penglongxiang** [comment]
Hi,

Currently there are no examples for pick and place, but there are Moveit support for Simulations and xarm_api and Moveit support for real arm applications, You can check the readme in detail and I believe you can develop it very fast.

**Comment by TZVIh** [comment]
Hi @santarone ,
Did you write some example?
Thanks
