### ISSUE TITLE
Fix for mimic_joint_plugin is incomplete 

### ISSUE THREAD

**Issue by jkaniuka** [xArm-Developer/xarm_ros#190]
In order for the gripper to work correctly in Gazebo, you need to change `libroboticsgroup_gazebo_mimic_joint_plugin.so` to `libroboticsgroup_upatras_gazebo_mimic_joint_plugin.so` in two files (not just in one as stated in the README now) : 

- xarm_ros/xarm_gripper/urdf/xarm_gripper.gazebo.xacro
- xarm_ros/xarm_description/urdf/gripper/xarm_gripper.gazebo.xacro

**Comment by Sakuraraa** [comment]
I fixed the gripper problem with your suggestions, thank you very much! #53

**Comment by jkaniuka** [comment]
Glad I could help :wink:
