### ISSUE TITLE
Unable to conver xarm7.urdf.xacro to URDF file

### ISSUE THREAD

**Issue by vivekcdavid** [xArm-Developer/xarm_ros#196]
I want to convert the[ xarm7.urdf.xacro](https://github.com/xArm-Developer/xarm_ros/blob/master/xarm_description/urdf/xarm7/xarm7.urdf.xacro)  file to a pure URDF file which I need for creating the IKfast plugin for the xarm7 robot. But the method to conver from .xacro.urdf to urdf is giving just the lines outside of the
 <xacro:macro .....> 
.....
...
</xacro:macro>

so the output is practically empty.
I am using  the following command to convert

rosrun xacro xacro xarm7.urdf.xacro> model.urdf 

Any help is appreciated

**Comment by vimior** [comment]
@vivekcdavid 
The wrong file was transferred. There are only macros defined in xarm7.urdf.xacro, but no calls. You should transfer (latest version) `xarm_description/urdf/xarm_device.urdf.xacro` or (previous version) `xarm_description/urdf/xarm7_robot.urdf .xacro`

**Comment by vivekcdavid** [comment]
Thank you so much, that worked.
