### ISSUE TITLE
文檔中提到xarm7的部分是否也都相容xarm6呢？

### ISSUE THREAD

**Issue by axacheng** [xArm-Developer/xarm_ros#2]
例如：roslaunch xarm7_moveit_config demo.launch 是否這個啟動檔也相容於xarm6？

如果我們下個月買的是xarm6是否這ROS workspace裡面的包都不支援呢？

謝謝

**Comment by axacheng** [comment]
阿！不好意思剛剛才看到「以下的指令说明是基于xArm7, 其他型号用户可以在对应位置将'xarm7'替换成'xarm6'或'xarm5'」

那是否所有包的 xarm7的功能我換成xarm6就可以動了呢？

**Comment by penglongxiang** [comment]
您好，是的ReadMe中的教程只使用xarm7作为示范，xarm6同样支持这些功能。您可以在仿真环境中将‘xarm7’替换为‘xarm6’试用。
