### ISSUE TITLE
About UF850 bringup driver and examples code

### ISSUE THREAD

**Issue by RoboDD** [xArm-Developer/xarm_ros#202]
Hi team,

Please let me know where the UF850 brings up the driver and its move-it config are.

Is there any ROS topic-based control API for joint velocity control or cartesian velocity control?

Thanks,
Bill

**Comment by vimior** [comment]
@RoboDD 
I added a new **xarm_bringup/launch/uf850_server.launch**, which can be used for updates.
In addition, regarding moveit control 850, you can use the `uf_robot_moveit_config` package

**Comment by RoboDD** [comment]
> @RoboDD I added a new **xarm_bringup/launch/uf850_server.launch**, which can be used for updates. In addition, regarding moveit control 850, you can use the `uf_robot_moveit_config` package

Thanks for your promote reply. It is very helpful. I will close the issue.
