### ISSUE TITLE
UFactory Lite 5 Model

### ISSUE THREAD

**Issue by DasGuna** [xArm-Developer/xarm_ros#206]
Are the URDF files for the lite 5 available (or similar to that of the xarm 5)? Thanks in advance.

**Comment by penglongxiang** [comment]
Hi, the `.xacro` files are available under `xarm_ros/xarm_description/urdf/xarm5` directory, if pure `.urdf` file is needed, please check the attached file(please modify the name to 'xarm5.urdf' or it will fail to upload here), it can be automatically generated by navigating to `xarm_ros/xarm_description/urdf` directory and execute: 

`rosrun xacro xacro xarm_device.urdf.xacro robot_type:=xarm dof:=5 --inorder > xarm5.urdf`

[xarm5.urdf.txt](https://github.com/xArm-Developer/xarm_ros/files/13915346/xarm5.urdf.txt)

**Comment by DasGuna** [comment]
Thanks for the clarification!
