### ISSUE TITLE
Xarm control using VR

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#210]
Hi, I would like to know how can I mimic the same result as [Video](https://www.youtube.com/watch?v=hK40Wzco_YY), I am getting the data and all , I just wanted to know which part of xarm API do I need to use to resolve this.

**Comment by penglongxiang** [comment]
Hi, I think it could be either servo_cartesian in mode 1 if the command update rate is high with low communication latency, or cartesian control in OTG mode 7 if the command is relatively sparse, just for your reference.
