### ISSUE TITLE
Online Target Update Example 

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#211]
Hi, I would like to know if you have any examples for using [OTG](https://github.com/xArm-Developer/xarm_ros/tree/master/examples#6-online-target-update) for XArm. Secondly I understand that this command 

`rosservice call /xarm/move_line [250,-100,400,3.14,0,0] 200 5000 0 0`

has the [x y z roll pitch yaw] but what are the other parameter in this command.

**Comment by penglongxiang** [comment]
You may check the message type of this service, and the definition is right here: https://github.com/xArm-Developer/xarm_ros/blob/master/xarm_msgs/srv/Move.srv
