### ISSUE TITLE
XArm Firmware Update 

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#212]
Hi, I am trying to update the firmware on XArm but it's saying 

![image](https://github.com/xArm-Developer/xarm_ros/assets/108360879/869a75ed-28a2-46a4-b8f5-13ff55dddfaa)

However for using [OTG](https://github.com/xArm-Developer/xarm_ros/tree/master/examples#6-online-target-update), It say's that 
`Now xArm controller (after firmware v1.11.0) supports Online Trajectory Generation (OTG) for both joint space and Cartesian space`
so with he current firmware I am not sure if I can still use OTG

**Comment by penglongxiang** [comment]
You may need to connect both your controller box and the PC to the internet. My colleague will help on this. Please note that the GUI of UF Studio will change if you upgrade to version 2.x.

**Comment by MinnaZhong** [comment]
Hi, 

Is the controller connected to the network? If not, please refer to the user manual Appendix 4 to offline upgrade the firmware and ufactorystudio to the latest V2.3.0 version.
https://drive.google.com/drive/folders/1WOcMMRXo0XACg48d3BR2Ki-kUKioCyGm?usp=drive_link
