### ISSUE TITLE
How to set the base of arm as coordinated frame

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#216]
Hello, I am trying to code Servo_Cartesian (streamed Cartesian trajectory) example , I would like to know what is the default coordinate system when using [Servo_Cartesian (streamed Cartesian trajectory)](https://github.com/xArm-Developer/xarm_ros/tree/master/examples) example,  I feel like currently it's TCP in my case , how can I change it to base, and if possible how can I give offset from my world frame. I read the [manual](file:///home/akumar/Downloads/xArm%20User%20Manual-V2.0.0-1.pdf) it tells us how can we do that in XArm Studio but I am not sure how can I do that in code.

**Comment by penglongxiang** [comment]
Please read the above mentioned section thoroughly, there are both base coordinate and tool coordinate example given. The switching parameter is the second last argument in the service call: 0 for base coordinate (absolute pose) and 1 for tool coordinate (relative pose). 

As for the world frame offset, you can set it up in xarm studio and it will take effect in ros service side (but not Moveit). You can also do it by calling `set_world_offset` service, the srv type format is [here](https://github.com/xArm-Developer/xarm_ros/blob/master/xarm_msgs/srv/TCPOffset.srv), it is the same type format with `set_tcp_offset`.
