### ISSUE TITLE
How can I use RS485 as  communication protocol instand of ip?

### ISSUE THREAD

**Issue by LinkZelad** [xArm-Developer/xarm_ros#22]

**Comment by penglongxiang** [comment]
Currently xarm_ros packages only support TCP/IP as communication interface. ROS Serial interface is under development.

**Comment by LinkZelad** [comment]
Tank you for your reply!And I have another question.Is there have a power management model in power saving?Due to I use  battery power.

**Comment by penglongxiang** [comment]
There is no power saving module inside, so it is better to cut-off the power while not in use,
