### ISSUE TITLE
Force-Torque sensor has no data response

### ISSUE THREAD

**Issue by taisi5446** [xArm-Developer/xarm_ros#222]
I using the xARM6 with FT sensor and gripper with jetson orin nano

But when i using roslaunch of realHW with report_type rich or dev, there are any data on xarm/uf_ftsensor_ext_states or xarm/uf_ftsensor_raw_states. (only has 0 0 0 0 0 0, no data change when i push or tilt FT sensor.)

How can i solve this problem?

![2024-03-31 21 17 17](https://github.com/xArm-Developer/xarm_ros/assets/72422809/79f54727-a991-4329-8c4c-d0dd0527e397)

And, FT-sensor control box has wrong letter on Robot side. Actual Robot socket is Force Torque sensor, and actual Force Torque socket is Robot. (in Robot side(upside) of picture, right line is actual robot socket, and middle line is actual FT-sensor )

**Comment by vimior** [comment]
@taisi5446 
1. Is the FT-sensor not enabled? Please refer to the #148 
2. Sorry, this sticker is an old model. I can confirm this is our latest design, the second head is for FT sensor, we will revise the sticker and user manual.

**Comment by taisi5446** [comment]
thank you for your advice.
I solved the problem and question.
