### ISSUE TITLE
How to add custom gripper using API 

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#225]
Hi, I wanted to know how can I add custom gripper to the arm using API, as I am using API to control the arm I want to use custom gripper with it , how can I do that. In addition to this how can I move the frame of reference to the TCP of gripper instead of arm TCP. Any help would be appreciated. 

Thank You

**Comment by penglongxiang** [comment]
Hi, you mentioned using the API, are you referring to xArm python SDK? And by "add custom gripper to the arm" did you mean adding it to self-collision model or how to control it using the end-tool comminication (RS-485)?

**Comment by penglongxiang** [comment]
Hi, please go to the C++ SDK [doc](https://github.com/xArm-Developer/xArm-CPLUS-SDK/blob/87f4735890a6e8e9daf7489db47a1bb085e85d81/doc/xarm_cplus_api.md) and check the `set_collision_tool_model` API, currently we did not support custom 3D mesh file, only approximated **cylinder** and **cubic** model. Also, there is currently no way to configure a surrounding environment in our SDK, you may try it with ROS.
