### ISSUE TITLE
Simulate Robot Mode 7 in Gazebo

### ISSUE THREAD

**Issue by nils-ingelhag** [xArm-Developer/xarm_ros#231]
Hi,

Is there a way to simulate the different operating modes in Gazebo? In particular I'm interested in running the Lite6 robot in mode 7 for real-time control.

Best,
Nils

**Comment by penglongxiang** [comment]
Hi @nils-ingelhag, currently there is no way to simulate our mode 7 in gazebo because it was implemented by our proprietary planner and mode management system, whereas Gazebo now uses ros-controllers with trajectory command from third party/self-implemented planners like Moveit.

**Comment by nils-ingelhag** [comment]
I see, thanks for your reply!
