### ISSUE TITLE
xarm6 - isaac sim - usd file

### ISSUE THREAD

**Issue by Murali25111993** [xArm-Developer/xarm_ros#235]
Hello,

I am working on nvidia isaac sim, for that we have to provide usd file. 

Many leading robotic arm manufacturer are providing with usd file, I had trouble in converting the urdf to usd file. 

Please provide the usd file for all your product.

The main objective for this is to working with nvidia - isaac_ros_manipulator [link](https://curobo.org/tutorials/1_robot_configuration.html).

Thanks,

**Comment by Murali25111993** [comment]
I have solved the issue. 

isaac_sim v 4.0.0

In case if anyone find difficulty in creating xrdf file. I am attching usd file , yaml file, xrdf file . 
![Screenshot from 2024-07-22 15-32-13](https://github.com/user-attachments/assets/bbb82e4b-4919-4e25-9a04-48f10e2582d8)
![Screenshot from 2024-07-24 11-56-41](https://github.com/user-attachments/assets/d5e6d0ee-cd37-43a1-8c13-c0e530700822)



[xarm6_1.zip](https://github.com/user-attachments/files/16358312/xarm6_1.zip)


Thanks

Murali

**Comment by Oliverbansk** [comment]
Hi! Thank you for your great effort! Can I ask if you have the USD file of xArm5 or xArm7 robot?

**Comment by m986883511** [comment]
![image](https://github.com/user-attachments/assets/34631154-4a5f-432f-8a1e-83f904e7239c)

can you control gripper use Gripper_Controller, I dont know how to set the params
![image](https://github.com/user-attachments/assets/5fd53667-e229-4f00-ba20-29bac5001592)

**Comment by Murali25111993** [comment]
No, I haven't tried using gripper. 

Thanks

**Comment by 23wjj** [comment]
> ![image](https://github.com/user-attachments/assets/34631154-4a5f-432f-8a1e-83f904e7239c)
> 
> can you control gripper use Gripper_Controller, I dont know how to set the params ![image](https://github.com/user-attachments/assets/5fd53667-e229-4f00-ba20-29bac5001592)

Hello, may I ask if you have the USD file of xarm7 with the gripper?

**Comment by inesdanjou** [comment]
Hello everyone, does anyone did a xArm7 usd file  with the bio_gripper ?
This file will really help me in my school project :)
