### ISSUE TITLE
mounting setting

### ISSUE THREAD

**Issue by TZVIh** [xArm-Developer/xarm_ros#30]
Hi,
I want to use wall mounting.
How can I send it using the node?
Thanks

**Comment by penglongxiang** [comment]
Hi, do you mean setting the model position in Gazebo simulation?

**Comment by TZVIh** [comment]
Hi,
I have XARM 5 LITE and I mount it in a wall mount.
If I work with XARM STUDIO I can tell the controller that I mount the robot in this position.
How can I tell it using ROS?
Thanks!

**Comment by penglongxiang** [comment]
Hi, mounting configuration should be done in xArm studio, there is no ROS interface. Because this is not a frequently changed configuration and in studio there is an intuitive model and guidance interface to set it correctly.

**Comment by TZVIh** [comment]
Thanks, I will check it
