### ISSUE TITLE
Adjusting teaching sensitivity through rosservice

### ISSUE THREAD

**Issue by RexDrac** [xArm-Developer/xarm_ros#37]
Hi,

I couldn't find the rosservice for adjusting the teach sensitivity for mode 2.
Are there any rosservice that can be used to adjust the teach sensitivity for zero gravity mode?

Thanks

**Comment by penglongxiang** [comment]
Hi, teaching sensitivity as a less frequently changed system configuration, currently is not available in ROS service, you can change it in xArm Studio user interface.
