### ISSUE TITLE
Xarm7: Joint 6 Issue

### ISSUE THREAD

**Issue by mmatsi** [xArm-Developer/xarm_ros#39]
Hello,
During usage of Xarm7 I am constantly heading with the following error:
![image](https://user-images.githubusercontent.com/57454715/93869380-67070100-fcd4-11ea-915a-d825c21e0da0.png)
This error comes up during usage of MoveIT, when controlling hand via Xarm Studio (web interface) and even when using joint teach mode. What makes hand usage almost impossible

**Comment by zfls** [comment]
Hello,
You can solve the issue through the following steps:
1) power off the xArm(press the emergency stop button)
2) power off the control box 
3) power on the control box
4) power on the xArm(rotate the emergency stop button)

If the problem still exists, please send the SN of the xArm base to us,thanks.

Best,

**Comment by mmatsi** [comment]
Thx for the quick reply
Unfortunatelly, it doesnt solve the problem. Could you please give me an email, where I can send the serial number. The serial number is located on the sticker control box?

**Comment by zfls** [comment]
Hello,
You can send the SN of the xArm to my email: shiyanfei@ufactory.cc
The SN of the xArm is shown in the picture below:
![hhhhhhhhhhhhhhh-05](https://user-images.githubusercontent.com/46313221/93892843-8e36f000-fd1f-11ea-95f4-f79d28a77953.jpg)
