### ISSUE TITLE
What are the DH parameters of Arm7

### ISSUE THREAD

**Issue by wangxdgg** [xArm-Developer/xarm_ros#41]
We are doing experiments, we want to get the DH parameters of Xarm7, and calculate them in Matlab

**Comment by penglongxiang** [comment]
You can check xArm DH parameters in our official articles at:  http://help.xarm.cc/en/articles/4330809-kinematic-and-dynamic-parameters-of-xarm-series

**Comment by crNewton** [comment]
link no longer works, here is the working url:
http://help.ufactory.cc/en/articles/4330809-kinematic-and-dynamic-parameters-of-xarm-series
