### ISSUE TITLE
xArm for ROS2

### ISSUE THREAD

**Issue by EgOrlukha** [xArm-Developer/xarm_ros#48]
Dear xArm developers,

thanks for your awesome product, it is a great solution for needs of our team.
Could you tell, is the current xarm_ros package compatible with ROS2? If no, do you plan transferring your progress to ROS2?

Thanks in advance!

**Comment by penglongxiang** [comment]
Hi @EgOrlukha ,

Glad you like our product and thank you for your support. Currently xarm_ros is not developed for ROS2 yet, we will do an evaluation and if there is a plan on supporting ROS2 next year, we will put up a notice in this repository.

**Comment by lorepieri8** [comment]
@penglongxiang Any updates on xArm on ROS2?

**Comment by penglongxiang** [comment]
@lorepieri8 We have development plan for ROS2 this year. However the release time is uncertain for now.

**Comment by penglongxiang** [comment]
@EgOrlukha @lorepieri8 Now the first version of  xArm for ROS2 is released. Please feel free to check and try out. Repository is at: (https://github.com/xArm-Developer/xarm_ros2). Please note that not all functions in xarm_ros are implemented as official ROS2 and related Moveit2 & Gazebo support are still under development.
