### ISSUE TITLE
xarm_api bug

### ISSUE THREAD

**Issue by swiz23** [xArm-Developer/xarm_ros#54]
The ROS Service for getting the current error message should return a boolean, but it does not. This results in a compilation time warning in ROS Noetic on Ubuntu 20.04. See the function at https://github.com/xArm-Developer/xarm_ros/blob/34e42794598c3ac2eefce37cf82767dbc9c85718/xarm_api/src/xarm_driver.cpp#L168

**Comment by penglongxiang** [comment]
Thank you for this bug report, already fixed it.
