### ISSUE TITLE
Rviz doesn't show the planned trajectory (trace)  

### ISSUE THREAD

**Issue by AnsunWu** [xArm-Developer/xarm_ros#57]
Hello,

Recently, I learned the package of MoveIt! and try to use X-arm to do some simulations.
I met with a problem: **RVIZ doesn't show the planned trajectory.**

The code in the "xarm_simple_planner.CPP" in the x-arm planner_package, the "rviz_visul_tool" is already being used to show the information and the planned trajectory in Rviz. (Shown below)

![image](https://user-images.githubusercontent.com/61506167/103471134-b4285380-4d56-11eb-8086-6ce3852b3ab6.png)
![image](https://user-images.githubusercontent.com/61506167/103471283-efc41d00-4d58-11eb-8f15-6149ad8f67f8.png)

And I also added the "Marker Array" tool in Rviz and subscribe to the right topic, the information is shown correctly:
![image](https://user-images.githubusercontent.com/61506167/103471159-34e74f80-4d57-11eb-9010-f14d64cbc849.png)

But when I executed the "pose planning code", the robot trajectory was now shown in Rviz as the code...
`rosservice call xarm_pose_plan 'target: [[0.28, 0.2, 0.2], [1.0, 0.0, 0.0, 0.0]]'
`
![image](https://user-images.githubusercontent.com/61506167/103471180-90194200-4d57-11eb-9c6a-d6251f039d7b.png)

**Could you please tell me how to let the rviz show the trajectory of the robot as in the picture below?**
![image](https://user-images.githubusercontent.com/61506167/103471207-05851280-4d58-11eb-9a7c-e058cd9e1dc2.png)

**I followed the detailed tutorial of the official moveit webpage and tried many ways to solve this problem, including **modifying the rviz environment, robot model in Moveit_setup_assistant,and modifying the code**...But still can not solve this problem.

Or is there any other way to show the trajectory like the picture above?
Many thanks for your help!!**

`http://docs.ros.org/en/kinetic/api/moveit_tutorials/html/doc/move_group_interface/move_group_interface_tutorial.html`

**Comment by AnsunWu** [comment]
@penglongxiang Solve the problem, the source of the question is :  
 there is no end effector link in the URDF(XACRO) file of the X-arm 5,6,7, and the function of `publishTrajectoryLine` is aimed to show the trace of the end-effector link. That's why the planned trajectory is not shown in RVIZ.

Solving method: 
1. Modify the URDF file of the X-arm robot, add an end effector link into it and use a fixed joint to connect the link6 with the end-effector link.
2. Use the "Moveit_setup_assistant" tool, add a "plan group" of the end-effector, set end-effector, and generate the .srdf and  .yaml file.
3. Done.

**Comment by penglongxiang** [comment]
@AnsunWu Thank you for providing the solution to this problem. Showing trajectory is originally intended but I did not achieve it successfully. We will fix this in next update.

**Comment by AnsunWu** [comment]
> @AnsunWu Thank you for providing the solution to this problem. Showing trajectory is originally intended but I did not achieve it successfully. We will fix this in next update.

No problem, Hope to do my development with the new update :)
I will close the issue.

Thanks,谢谢。

**Comment by penglongxiang** [comment]
Hi @AnsunWu, we have fixed the trajectory visualization issue, please refer [here](https://github.com/xArm-Developer/xarm_ros/tree/master/xarm_planner) and update your local repository, you can now use xarm models with UF gripper or vacuum gripper attached in 'xarm_planner'.

**Comment by AnsunWu** [comment]
@penglongxiang Hello, Thanks for the quick update!
