### ISSUE TITLE
Access Control box Analog Pins?

### ISSUE THREAD

**Issue by ivanrulik** [xArm-Developer/xarm_ros#58]
Hi is it possible to access the analog pins of the control box using this library or the only way is using the python SDK?

Thank you,

Ivan

**Comment by penglongxiang** [comment]
Hi @ivanrulik , currently controller analog IO is not wrapped as ROS service interface yet, we will provide it ASAP in the following update.

**Comment by penglongxiang** [comment]
Hi, analog pins of the control box can now be accessed through ros service, please update your local repository and refer to: https://github.com/xArm-Developer/xarm_ros#3-to-get-one-of-the-controller-analog-input

**Comment by ivanrulik** [comment]
Thanks! You are Awesome!!
