### ISSUE TITLE
Question regarding Ethernet cable

### ISSUE THREAD

**Issue by JuliusSustarevas** [xArm-Developer/xarm_ros#68]
Hi, apologies if this isn't the right place. I have been seing really good support there, so I'm writing here. 

I am adding a network switch between arm and PC. However, I want to use a 100mb (4 wires total) switch. I know the ethernet cable provided is a gigabit(8 wires total) but  I can't see anywhere that says 1000mbps is a hard requirement.  Would you anticipate issues with 100mbps connection?

**Comment by penglongxiang** [comment]
Hi, we have not done specific test for 100Mb case, but I suppose it would not be a issue since normally the data exchange rate with xArm controller is just at KB level.
