### ISSUE TITLE
How to add camera link and self made gripper

### ISSUE THREAD

**Issue by Aki92-Xavier** [xArm-Developer/xarm_ros#86]
Hi,I made my own gripper with realsense D435. How should I edit the Urdf file.

![498B1E95-78B3-4EE4-A065-EAADD811FCC5](https://user-images.githubusercontent.com/86097846/135836139-8622a058-8a9f-4589-ac54-0925c1e93ee5.jpeg)

**Comment by penglongxiang** [comment]
hi @Aki92-Xavier, if you have the gripper 3D model, please refer to [this instruction](https://github.com/xArm-Developer/xarm_ros#551-add-custom-tool-model-for-moveit), use `mesh` as `geometry_type` and specify the proper mesh file location and offset parameters.
