### ISSUE TITLE
Q on power/connection loss safety

### ISSUE THREAD

**Issue by JuliusSustarevas** [xArm-Developer/xarm_ros#90]
Hi a quick question on what happens in case of power loss or network loss. Could you please describe what happens in these scenarios:

All scenarios have xarm dc control box, xarm 6 and a control PC like intel nuc.  PC and dc control box are connected via ethernet via a switch/router

A: PC is sending joint velocity commands to xarm using the velocity hardware interface running on the PC.   A1: will the arm keep moving if PC loses power?  A2: will the arm keep moving if PC looses networking?

B: What are the general consequences/risks of DC control box losing power while moving.

**Comment by penglongxiang** [comment]
Hi, please first update "xarm_ros" and controller firmware to the latest versions. If the robot is controlled by velocity hardware interface, the default update timeout is **1 second**, which means if PC loses power or network connection, robot will stop after 1 second.

If xArm is controlled via ros service, please refer [here](https://github.com/xArm-Developer/xarm_ros/issues/90) and use `/xarm/velo_move_joint_timed` or `/xarm/velo_move_line_timed` services to specify a time-out value for safety. 

As for losing power of DC control box, the robot will stop immediately but it may not be good for the brakes if the speed is high.
