### ISSUE TITLE
ask some questions

### ISSUE THREAD

**Issue by jzx-gooner** [xArm-Developer/xarm_ros#91]
1. `roslaunch xarm_description xarm7_rviz_display.launch`  the modle is not good ,and the error in rviz  `No tf data.  Actual error: Fixed Frame [world] does not exist`  and the error `No transform from [link1] to [world]`in robotmodel
2. `$ roslaunch xarm_gazebo xarm7_beside_table.launch [run_demo:=true] [add_gripper:=true] [add_vacuum_gripper:=true] ` the model is not good ,wihtout gripper and do not run the trajectory move.
3. `rosrun xarm_gazebo color_recognition.py` modify to python2 and seems it do not work to grasp.
Thank you very much!

**Comment by penglongxiang** [comment]
1. This launch script behaves normally on our side. Please make sure all dependencies have been properly installed. If issue still persists, please tell us your running environment and ROS version.
2. Try removing the brackets `[ ]` if you have added them in command line. Here, they supposed to mean "optional arguments", and please note you can not add the gripper and vaccum_gripper at the same time. 
3. This script is still under test, and not yet appeared in our ReadMe. Please do not use it yet with python2.

**Comment by jzx-gooner** [comment]
Thank you for your help.the problem solved!
