### ISSUE TITLE
Update xarm_sdk submodule

### ISSUE THREAD

**Issue by BryanStuurman** [xArm-Developer/xarm_ros#94]
The xarm_sdk submodule points to an old commit of xArm-CPLUS-SDK (cxx @ 458d533) which is no longer compatible with the current xarm_ros code. The solution being advertised is to perform a `git submodule update --remote` which bypasses the specified commit and gets the most recent version of the SDK.

Can we just commit an updated pointer to xArm-CPLUS-SDK?

**Comment by penglongxiang** [comment]
Hi @BryanStuurman , thank you for finding out the issue, ther pointed version has been updated now.

**Comment by BryanStuurman** [comment]
Excellent, thanks!
